server:
  port: 9090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/BurgerStoreKullaniciDB
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
